### ISSUE TITLE
We are getting error while executing through XLdeploy on Windows

### ISSUE THREAD

**Issue by anand1312** [xebialabs-community/xld-powercenter-plugin#1]
Error description :+1: 
 
-------------------------------------------------------------------------------------------------------------------The description for Event ID 1141 from source pmrep cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

ERROR: This application has failed to allocate more memory.Application terminating. You can either increase the physical memory size on this host or contact Informatica Technical Support for assistance.

Thanks,
Anand
![windows_logs_11142016](https://cloud.githubusercontent.com/assets/23665084/20539710/04ddccf8-b0c4-11e6-9465-6aefd900fbf0.JPG)

**Comment by jdewinne** [comment]
Can you elaborate a little bit more on when you're getting this error? Like which step in XLD is showing this, so we can potentially identify the corresponding script.

**Comment by anand1312** [comment]
Hi,

We are facing issues while executing pmrep validate command.

Last command in the attached script.

Moreover, we are getting this error only while executing through XLD. We are able to execute it manually from XL deploy server.
![capture](https://cloud.githubusercontent.com/assets/23665084/20541652/28cd9708-b0cc-11e6-85f1-280912d67a12.JPG)


[powercenter_install.bat.ftl.txt](https://github.com/xebialabs-community/xld-powercenter-plugin/files/607561/powercenter_install.bat.ftl.txt)

**Comment by jdewinne** [comment]
This looks like your objectimport returns an exit code 6. Can you check on why that is the case?

**Comment by anand1312** [comment]
Objectimport command runs fine. we are facing issue while executing {pmrep} validate

validate returns code 6 because of the exception in windows logs (screenshot already attached)

-------------------------------------------------------------------------------------------------------------------
description for Event ID 1141 from source pmrep cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event:

ERROR: This application has failed to allocate more memory.Application terminating. You can either increase the physical memory size on this host or contact Informatica Technical Support for assistance
-----------------------------------------------------------------------------------------------------------------

**Comment by anand1312** [comment]
log :

------------------------------------------------------------------------------------------------------------------------------------------------------------------
Uploading artifact [C:\windows\temp\ot-20161123T131653450.1\wf_s_m_xld_GPtest.XML]
Copying C:\windows\temp\ot-20161123T131653450.1\wf_s_m_xld_GPtest.XML to C:\windows\temp\ot-20161123T131653450\working.directory.tmp\xld.2861\wf_s_m_xld_GPtest.XML on host Infrastructure/GP/etl
Creating path C:\windows\temp\ot-20161123T131653450\working.directory.tmp\powercenter\ on host Infrastructure/GP/etl
Processing freemarker template powercenter/powercenter_install.bat.ftl to C:\windows\temp\ot-20161123T131653450\working.directory.tmp\powercenter\powercenter_install.bat
Copying resource file:/D:/NJM/XLDeploy/xl-deploy-5.5.5-server/ext/powercenter/impcntl.dtd to C:\windows\temp\ot-20161123T131653450\working.directory.tmp\powercenter\impcntl.dtd on host Infrastructure/GP/etl
Processing freemarker template powercenter/powercenter_controlfile.xml.ftl to C:\windows\temp\ot-20161123T131653450\working.directory.tmp\powercenter\powercenter_controlfile.xml
Executing C:\windows\temp\ot-20161123T131653450\working.directory.tmp\powercenter\powercenter_install.bat on host Infrastructure/GP/etl
Informatica(r) PMREP, version [9.6.1 HotFix2], build [921.0115], Windows 32-bit
Copyright (c) Informatica Corporation 1994 - 2015
All Rights Reserved.
This Software is protected by U.S. Patent Numbers 5,794,246; 6,014,670; 6,016,501; 6,029,178; 6,032,158; 6,035,307; 6,044,374; 6,092,086; 6,208,990; 6,339,775; 6,640,226; 6,789,096; 6,823,373; 6,850,947; 6,895,471; 7,117,215; 7,162,643; 7,243,110; 7,254,590; 7,281,001; 7,421,458; 7,496,588; 7,523,121; 7,584,422; 7,676,516; 7,720,842; 7,721,270; 7,774,791; 8,065,266; 8,150,803; 8,166,048; 8,166,071; 8,200,622; 8,224,873; 8,271,477; 8,327,419; 8,386,435; 8,392,460; 8,453,159; 8,458,230; 8,707,336; 8,886,617; and RE44,478, International Patents and other Patents Pending.
Invoked at Wed Nov 23 13:16:54 2016
Connected to repository ETLBATCHQ2WT1_RepositoryService in Domain_ETLQ2WT1 as user GS6812
connect completed successfully.
Completed at Wed Nov 23 13:16:59 2016
Informatica(r) PMREP, version [9.6.1 HotFix2], build [921.0115], Windows 32-bit
Copyright (c) Informatica Corporation 1994 - 2015
All Rights Reserved.
This Software is protected by U.S. Patent Numbers 5,794,246; 6,014,670; 6,016,501; 6,029,178; 6,032,158; 6,035,307; 6,044,374; 6,092,086; 6,208,990; 6,339,775; 6,640,226; 6,789,096; 6,823,373; 6,850,947; 6,895,471; 7,117,215; 7,162,643; 7,243,110; 7,254,590; 7,281,001; 7,421,458; 7,496,588; 7,523,121; 7,584,422; 7,676,516; 7,720,842; 7,721,270; 7,774,791; 8,065,266; 8,150,803; 8,166,048; 8,166,071; 8,200,622; 8,224,873; 8,271,477; 8,327,419; 8,386,435; 8,392,460; 8,453,159; 8,458,230; 8,707,336; 8,886,617; and RE44,478, International Patents and other Patents Pending.
Invoked at Wed Nov 23 13:16:59 2016
objectimport completed successfully.
Completed at Wed Nov 23 13:17:09 2016
Informatica(r) PMREP, version [9.6.1 HotFix2], build [921.0115], Windows 32-bit
Copyright (c) Informatica Corporation 1994 - 2015
All Rights Reserved.
This Software is protected by U.S. Patent Numbers 5,794,246; 6,014,670; 6,016,501; 6,029,178; 6,032,158; 6,035,307; 6,044,374; 6,092,086; 6,208,990; 6,339,775; 6,640,226; 6,789,096; 6,823,373; 6,850,947; 6,895,471; 7,117,215; 7,162,643; 7,243,110; 7,254,590; 7,281,001; 7,421,458; 7,496,588; 7,523,121; 7,584,422; 7,676,516; 7,720,842; 7,721,270; 7,774,791; 8,065,266; 8,150,803; 8,166,048; 8,166,071; 8,200,622; 8,224,873; 8,271,477; 8,327,419; 8,386,435; 8,392,460; 8,453,159; 8,458,230; 8,707,336; 8,886,617; and RE44,478, International Patents and other Patents Pending.
Invoked at Wed Nov 23 13:17:09 2016
The total number of records returned: 90
executequery completed successfully.
Completed at Wed Nov 23 13:17:44 2016
Validation: 
Execution failed with exit code 6

**Comment by jdewinne** [comment]
ok. But where is `pmrep validate` being executed? At this moment, the plugin is only executing objectimport. So are you using a customized version? And of course the exception seems to be coming from pmrep, so I assume something is wrong on that side. not?

**Comment by anand1312** [comment]
We have customized and added pmrep validate command for our needs and it is important for us.
The exception appears to be coming from pmrep. However, the key point is that the error comes only when we perform deployments using XLDeploy. We are able to execute the script manually.

**Comment by jdewinne** [comment]
When you exit manually, do you also check for the exitcode?
I can see you're running this on a windows box. Do you know how winrm is configured and what the memory settings are? For example, when using `winrm native`, this has some options to configure the memory settings [Configuration](https://docs.xebialabs.com/xl-deploy/how-to/set-up-winrm-in-xl-deploy-and-on-a-target-host.html).
