### ISSUE TITLE
XLDeploy deleting already deployed parameter files

### ISSUE THREAD

**Issue by okram999** [xebialabs-community/xld-powercenter-plugin#12]
How can we disable the feature that XLDeploy deletes a previously deployed parameter files, if its not a part of the subsequent package that was created.

**Comment by jdewinne** [comment]
How about [disabling the rule](https://docs.xebialabs.com/xl-deploy/how-to/disable-a-rule.html) `powercenter.DeployedPowercenterXml.DESTROY` in `ext/xl-rules.xml`

**Comment by okram999** [comment]
@jdewinne  i did applied a similiar rule in the plugin's 'xl-rules.xml' , but it doesn't do anything.. Is there a way that i can control this entirely from the plugin's file. Rather than on a GLOBAL file ('ext/xl-rules.xml') ?  


UPDATE: 
did you mean: **powercenter.DeployedPowercenterParamFile** ??? i am not looking for the XML rule, but rather the new type for files


Moreover, it says the _"cannot be disable since it doesn't exist in the registry"_
