### ISSUE TITLE
dynamic control file

### ISSUE THREAD

**Issue by anand1312** [xebialabs-community/xld-powercenter-plugin#2]
Hi, 

When we try with the process mentioned, We get exception as cannot find the control file.

It works fine when we place the hard-coded control file in the directory. 

Is there a way if we can pull the control file dynamically.

Thanks,
Anand

**Comment by jdewinne** [comment]
What do you mean with a hard-coded control file? At this moment the control file is part of the plugin, which means you can also override it by placing your own version under the `ext/powercenter` folder.
+ [xl-rules](https://github.com/xebialabs-community/xld-powercenter-plugin/blob/master/src/main/resources/xl-rules.xml#L23)
+ [Install script](https://github.com/xebialabs-community/xld-powercenter-plugin/blob/master/src/main/resources/powercenter/powercenter_install.sh.ftl#L23)

**Comment by anand1312** [comment]
We are using v1.0.5 plugin.

**Comment by jdewinne** [comment]
Maybe upgrade to v1.0.6? I still don't think I really understand what you're trying to achieve. Can you elaborate a bit more?

**Comment by okram999** [comment]
@jdewinne may be the request is to allow customization of the control file. .. At this point, the plugin assumes that the target folder is going to be the same as the source folder. 

What about the workflows that shared objects like mappings? Workflows which uses shared mappings will need 2/more source folders and target folders. This plugin only works for very simple imports. 

i don't have a good understanding of XLdeploy yet, but will love to contribute with some feature changes.

**Comment by jdewinne** [comment]
See [v1.1.2](https://github.com/xebialabs-community/xld-powercenter-plugin/releases/tag/v1.1.2)
