### ISSUE TITLE
usability

### ISSUE THREAD

**Issue by okram999** [xebialabs-community/xld-powercenter-plugin#3]
How do i use this plugin in a local xl deploy instance? Would you be kind enough to add some steps in the README.md file? I just installed XL Deploy and 30mins ago, i didn't knew there is something called XL Deploy.

**Comment by jdewinne** [comment]
Maybe a good starting point might be the XLD [videos](https://docs.xebialabs.com/xl-deploy/). And based on that you might have some more specific questions.

**Comment by okram999** [comment]
@jdewinne thanks this https://docs.xebialabs.com/xl-deploy/how-to/install-or-remove-xl-deploy-plugins.html have the answer.
