### ISSUE TITLE
Deployments failing with the new release. 

### ISSUE THREAD

**Issue by okram999** [xebialabs-community/xld-powercenter-plugin#7]
Somnething is wrong with the control file. The object imports fails with the XML of the control file. Part of the console error:

All Rights Reserved.
This Software is protected by U.S. Patent Numbers 5,794,246; 6,014,670; 6,016,501; 6,029,178; 6,032,158; 6,035,307; 6,044,374; 6,092,086; 6,208,990; 6,339,775; 6,640,226; 6,789,096; 6,820,077; 6,823,373; 6,850,947; 6,895,471; 7,117,215; 7,162,643; 7,243,110; 7,254,590; 7,281,001; 7,421,458; 7,496,588; 7,523,121; 7,584,422; 7,676,516; 7,720,842; 7,721,270; and 7,774,791, international Patents and other Patents Pending.
Invoked at Tue Feb 21 22:35:50 2017
Connected to repository TST in Domain_informaticaLinux as user Administrator
connect completed successfully.
Completed at Tue Feb 21 22:35:55 2017
------------------------------------------------------------------------
Informatica(r) PMREP, version [9.5.1 HotFix2], build [231.0621], LINUX 64-bit
Copyright (c) Informatica Corporation 1994 - 2013
All Rights Reserved.
This Software is protected by U.S. Patent Numbers 5,794,246; 6,014,670; 6,016,501; 6,029,178; 6,032,158; 6,035,307; 6,044,374; 6,092,086; 6,208,990; 6,339,775; 6,640,226; 6,789,096; 6,820,077; 6,823,373; 6,850,947; 6,895,471; 7,117,215; 7,162,643; 7,243,110; 7,254,590; 7,281,001; 7,421,458; 7,496,588; 7,523,121; 7,584,422; 7,676,516; 7,720,842; 7,721,270; and 7,774,791, international Patents and other Patents Pending.
Invoked at Tue Feb 21 22:35:55 2017
Error at (file /tmp/ot-20170222T043548778/working.directory.tmp/powercenter/powercenter_controlfile.xml, line 26, char 1 ): No character data is allowed by content model.
Failed to execute objectimport.
Completed at Tue Feb 21 22:36:00 2017
[ERROR]: Execution failed with exit code 1

Info: 19e785c9-c07e-4405-bbc1-ee5269cdc7ea step #2 PENDING	Register deployeds
ERROR: An error during the deployment com.xebialabs.deployit.ci.DeployitPluginException: deployit-plugin: deployit-plugin: Error when executing task 19e785c9-c07e-4405-bbc1-ee5269cdc7ea
Build step 'Deploy with XL Deploy' marked build as failure
Finished: FAILURE

**Comment by okram999** [comment]
issue with line#32..  https://github.com/xebialabs-community/xld-powercenter-plugin/blob/master/src/main/resources/powercenter/powercenter_controlfile.xml.ftl#L32

**Comment by vlussenburg** [comment]
@droberts2013 @gsajwan seems like @okram999 has a good point.. can you fix and nuke the released version?

**Comment by okram999** [comment]
@vlussenburg you missed to remove the extra '>' in https://github.com/xebialabs-community/xld-powercenter-plugin/blob/9b533c779d24868a5cfa5ead8264d6b80fa97c7e/src/main/resources/powercenter/powercenter_controlfile.xml.ftl#L32
